<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  
  <PropertyGroup>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

	<PropertyGroup>
		<!-- Path to Opus Magnum folder, Contains Lightning.exe et.al -->
		<OpusDir>D:\C#_projects\UnstableElements\UnstableElements\bin\Debug\TestEnvironment\modded</OpusDir>
	</PropertyGroup>

  <ItemGroup>
    <Reference Include="Lightning">
      <HintPath>$(OpusDir)\DevLightning.dll</HintPath>
      <CopyLocal>False</CopyLocal>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>$(OpusDir)\Mono.Cecil.dll</HintPath>
      <CopyLocal>False</CopyLocal>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>$(OpusDir)\MonoMod.Utils.dll</HintPath>
      <CopyLocal>False</CopyLocal>
    </Reference>
    <Reference Include="YamlDotNet">
      <HintPath>$(OpusDir)\YamlDotNet.dll</HintPath>
      <CopyLocal>False</CopyLocal>
    </Reference>
  </ItemGroup>

</Project>
